### ISSUE TITLE
Errors with the old version in the classpath

### ISSUE THREAD

**Issue by apatrida** [Kotlin/kotlinx.reflect.lite#9]
IDE indexing doesn't like the 1038 versino

```
Error while indexing /Users/jminard/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlinx/kotlinx.reflect.lite/1.0.0-beta-1038/da6b747014cae64c86606d8627cb4ee5c35d4148/kotlinx.reflect.lite-1.0.0-beta-1038.jar!/a/a/a/a/a/a.class
To reindex this file IDEA has to be restarted: Could not find class data for nested class Companion of class a/a/a/a/a/a
java.lang.AssertionError: Could not find class data for nested class Companion of class a/a/a/a/a/a
    at org.jetbrains.kotlin.idea.decompiler.stubBuilder.ClassClsStubBuilder.createNestedClassStub(ClassClsStubBuilder.kt:237)
    at org.jetbrains.kotlin.idea.decompiler.stubBuilder.ClassClsStubBuilder.createCompanionObjectStub(ClassClsStubBuilder.kt:171)
    at org.jetbrains.kotlin.idea.decompiler.stubBuilder.ClassClsStubBuilder.createClassBodyAndMemberStubs(ClassClsStubBuilder.kt:160)
    at org.jetbrains.kotlin.idea.decompiler.stubBuilder.ClassClsStubBuilder.build(ClassClsStubBuilder.kt:74)
    at org.jetbrains.kotlin.idea.decompiler.stubBuilder.ClassClsStubBuilderKt.createClassStub(ClassClsStubBuilder.kt:43)
    at org.jetbrains.kotlin.idea.decompiler.stubBuilder.ClsStubBuildingKt.createTopLevelClassStub(clsStubBuilding.kt:44)
    at org.jetbrains.kotlin.idea.decompiler.classFile.KotlinClsStubBuilder.doBuildFileStub(KotlinClsStubBuilder.kt:90)
    at org.jetbrains.kotlin.idea.decompiler.classFile.KotlinClsStubBuilder.buildFileStub(KotlinClsStubBuilder.kt:57)
    at com.intellij.psi.impl.compiled.ClassFileStubBuilder.buildStubTree(ClassFileStubBuilder.java:58)
    at com.intellij.psi.impl.compiled.ClassFileStubBuilder.buildStubTree(ClassFileStubBuilder.java:38)
    at com.intellij.psi.stubs.StubTreeBuilder.buildStubTree(StubTreeBuilder.java:63)
    at com.intellij.psi.stubs.StubUpdatingIndex$3$1.run(StubUpdatingIndex.java:127)
    at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:947)
    at com.intellij.psi.stubs.StubUpdatingIndex$3.map(StubUpdatingIndex.java:124)
    at com.intellij.psi.stubs.StubUpdatingIndex$3.map(StubUpdatingIndex.java:118)
    at com.intellij.util.indexing.MapReduceIndex.update(MapReduceIndex.java:398)
    at com.intellij.util.indexing.FileBasedIndexImpl.updateSingleIndex(FileBasedIndexImpl.java:1815)
    at com.intellij.util.indexing.FileBasedIndexImpl$23.run(FileBasedIndexImpl.java:1744)
    at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.freezeFileTypeTemporarilyIn(FileTypeManagerImpl.java:504)
    at com.intellij.util.indexing.FileBasedIndexImpl.a(FileBasedIndexImpl.java:1702)
    at com.intellij.util.indexing.FileBasedIndexImpl.indexFileContent(FileBasedIndexImpl.java:1687)
    at com.intellij.util.indexing.UnindexedFilesUpdater$2.consume(UnindexedFilesUpdater.java:108)
    at com.intellij.util.indexing.UnindexedFilesUpdater$2.consume(UnindexedFilesUpdater.java:105)
    at com.intellij.openapi.project.CacheUpdateRunner$MyRunnable$1.run(CacheUpdateRunner.java:233)
    at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1180)
    at com.intellij.openapi.project.CacheUpdateRunner$MyRunnable$2.run(CacheUpdateRunner.java:253)
    at com.intellij.openapi.progress.impl.CoreProgressManager$2.run(CoreProgressManager.java:142)
    at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:446)
    at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:443)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
    at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:127)
    at com.intellij.openapi.project.CacheUpdateRunner$MyRunnable.run(CacheUpdateRunner.java:247)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at com.intellij.util.concurrency.BoundedTaskExecutor$2.run(BoundedTaskExecutor.java:169)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
    at org.jetbrains.ide.PooledThreadExecutor$2$1.run(PooledThreadExecutor.java:71)



java.lang.AssertionError: Could not find class data for nested class PropertySignature of class a/a/a/c/b/v
    at org.jetbrains.kotlin.idea.decompiler.stubBuilder.ClassClsStubBuilder.createNestedClassStub(ClassClsStubBuilder.kt:237)
    at org.jetbrains.kotlin.idea.decompiler.stubBuilder.ClassClsStubBuilder.createInnerAndNestedClasses(ClassClsStubBuilder.kt:230)
    at org.jetbrains.kotlin.idea.decompiler.stubBuilder.ClassClsStubBuilder.createClassBodyAndMemberStubs(ClassClsStubBuilder.kt:162)
    at org.jetbrains.kotlin.idea.decompiler.stubBuilder.ClassClsStubBuilder.build(ClassClsStubBuilder.kt:74)
    at org.jetbrains.kotlin.idea.decompiler.stubBuilder.ClassClsStubBuilderKt.createClassStub(ClassClsStubBuilder.kt:43)
    at org.jetbrains.kotlin.idea.decompiler.stubBuilder.ClsStubBuildingKt.createTopLevelClassStub(clsStubBuilding.kt:44)
    at org.jetbrains.kotlin.idea.decompiler.classFile.KotlinClsStubBuilder.doBuildFileStub(KotlinClsStubBuilder.kt:90)
    at org.jetbrains.kotlin.idea.decompiler.classFile.KotlinClsStubBuilder.buildFileStub(KotlinClsStubBuilder.kt:57)
    at com.intellij.psi.impl.compiled.ClassFileStubBuilder.buildStubTree(ClassFileStubBuilder.java:58)
    at com.intellij.psi.impl.compiled.ClassFileStubBuilder.buildStubTree(ClassFileStubBuilder.java:38)
    at com.intellij.psi.stubs.StubTreeBuilder.buildStubTree(StubTreeBuilder.java:63)
    at com.intellij.psi.stubs.StubUpdatingIndex$3$1.run(StubUpdatingIndex.java:127)
    at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:947)
    at com.intellij.psi.stubs.StubUpdatingIndex$3.map(StubUpdatingIndex.java:124)
    at com.intellij.psi.stubs.StubUpdatingIndex$3.map(StubUpdatingIndex.java:118)
    at com.intellij.util.indexing.MapReduceIndex.update(MapReduceIndex.java:398)
    at com.intellij.util.indexing.FileBasedIndexImpl.updateSingleIndex(FileBasedIndexImpl.java:1815)
    at com.intellij.util.indexing.FileBasedIndexImpl$23.run(FileBasedIndexImpl.java:1744)
    at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.freezeFileTypeTemporarilyIn(FileTypeManagerImpl.java:504)
    at com.intellij.util.indexing.FileBasedIndexImpl.a(FileBasedIndexImpl.java:1702)
    at com.intellij.util.indexing.FileBasedIndexImpl.indexFileContent(FileBasedIndexImpl.java:1687)
    at com.intellij.util.indexing.UnindexedFilesUpdater$2.consume(UnindexedFilesUpdater.java:108)
    at com.intellij.util.indexing.UnindexedFilesUpdater$2.consume(UnindexedFilesUpdater.java:105)
    at com.intellij.openapi.project.CacheUpdateRunner$MyRunnable$1.run(CacheUpdateRunner.java:233)
    at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1180)
    at com.intellij.openapi.project.CacheUpdateRunner$MyRunnable$2.run(CacheUpdateRunner.java:253)
    at com.intellij.openapi.progress.impl.CoreProgressManager$2.run(CoreProgressManager.java:142)
    at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:446)
    at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:443)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
    at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:127)
    at com.intellij.openapi.project.CacheUpdateRunner$MyRunnable.run(CacheUpdateRunner.java:247)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at com.intellij.util.concurrency.BoundedTaskExecutor$2.run(BoundedTaskExecutor.java:169)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
    at org.jetbrains.ide.PooledThreadExecutor$2$1.run(PooledThreadExecutor.java:71)




```

**Comment by udalov** [comment]
What's the version of your Kotlin plugin?

**Comment by apatrida** [comment]
4589
